import {
  Task,
  Project,
  Goal,
  Duty,
  Deadline,
  CalendarEvent,
  NotificationItem,
  Activity,
  DailyReview,
  WeeklyReview,
} from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "SynaptiQ",
    description: "Distributed neural orchestration and low-latency API gateway",
    progress: 82,
    totalTasks: 15,
    completedTasks: 12,
    upcomingDeadline: "Backend deployment",
    lastActivity: "12m ago",
    status: "active",
    category: "Engineering",
  },
  {
    id: "proj-2",
    name: "FluentX",
    description: "Voice-driven microservices & real-time telemetry streaming",
    progress: 65,
    totalTasks: 20,
    completedTasks: 13,
    upcomingDeadline: "Telemetry beta release",
    lastActivity: "2h ago",
    status: "active",
    category: "Architecture",
  },
  {
    id: "proj-3",
    name: "Personal",
    description: "Physical conditioning, health metrics, and living space optimization",
    progress: 54,
    totalTasks: 10,
    completedTasks: 5,
    upcomingDeadline: "Q4 Conditioning benchmark",
    lastActivity: "4h ago",
    status: "active",
    category: "Lifestyle",
  },
  {
    id: "proj-4",
    name: "Learning",
    description: "Deep dive into High-Performance FastAPI and Distributed Systems in Go",
    progress: 78,
    totalTasks: 14,
    completedTasks: 11,
    upcomingDeadline: "FastAPI Concurrency certification",
    lastActivity: "Yesterday",
    status: "active",
    category: "Knowledge",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "TASK-101",
    title: "Fix OAuth redirect",
    description: "Resolve callback URL mismatch and state nonce verification in auth gateway handler.",
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "urgent",
    status: "pending",
    dueDate: "2026-10-07",
    dueTime: "18:00",
    durationMinutes: 45,
    tags: ["auth", "security", "bugfix"],
    reminder: "15m before",
    repeat: "Never",
    attachmentsCount: 2,
    createdAt: "2026-10-06T10:00:00Z",
    updatedAt: "2026-10-07T18:00:00Z",
  },
  {
    id: "TASK-102",
    title: "Review backend API",
    description: "Verify Pydantic v2 serialization schemas and endpoint response times under 40ms.",
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "high",
    status: "pending",
    dueDate: "2026-10-08",
    dueTime: "14:00",
    durationMinutes: 60,
    tags: ["fastapi", "perf", "schemas"],
    reminder: "30m before",
    repeat: "Never",
    attachmentsCount: 1,
    createdAt: "2026-10-07T09:00:00Z",
    updatedAt: "2026-10-08T09:00:00Z",
  },
  {
    id: "TASK-103",
    title: "SynaptiQ backend",
    description: "Implement token bucket rate limiter and async Redis connection pool orchestration.",
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "urgent",
    status: "pending",
    dueDate: "2026-10-08",
    dueTime: "18:30",
    durationMinutes: 90,
    tags: ["core", "redis", "async"],
    reminder: "15m before",
    repeat: "Never",
    attachmentsCount: 3,
    createdAt: "2026-10-08T08:00:00Z",
    updatedAt: "2026-10-08T14:00:00Z",
  },
  {
    id: "TASK-104",
    title: "Prepare project documentation",
    description: "Write architectural design doc for FastAPI ingestion pipeline and schema migrations.",
    projectId: "proj-2",
    projectName: "FluentX",
    priority: "medium",
    status: "pending",
    dueDate: "2026-10-09",
    dueTime: "16:00",
    durationMinutes: 75,
    tags: ["docs", "rfc", "architecture"],
    reminder: "1h before",
    repeat: "Never",
    attachmentsCount: 0,
    createdAt: "2026-10-07T11:00:00Z",
    updatedAt: "2026-10-08T11:00:00Z",
  },
  {
    id: "TASK-105",
    title: "Study FastAPI concurrency model",
    description: "Benchmark AnyIO threadpool workers vs native async event loop task scheduling.",
    projectId: "proj-4",
    projectName: "Learning",
    priority: "medium",
    status: "pending",
    dueDate: "2026-10-08",
    dueTime: "21:00",
    durationMinutes: 60,
    tags: ["learning", "python", "async"],
    reminder: "15m before",
    repeat: "Daily",
    attachmentsCount: 1,
    createdAt: "2026-10-08T07:00:00Z",
    updatedAt: "2026-10-08T07:00:00Z",
  },
  {
    id: "TASK-106",
    title: "Workout: Conditioning & Mobility",
    description: "Compound strength circuit: 5x5 deadlifts, kettlebell swings, 15m mobility cooldown.",
    projectId: "proj-3",
    projectName: "Personal",
    priority: "high",
    status: "pending",
    dueDate: "2026-10-08",
    dueTime: "18:30",
    durationMinutes: 60,
    tags: ["fitness", "health", "strength"],
    reminder: "15m before",
    repeat: "Daily",
    attachmentsCount: 0,
    createdAt: "2026-10-08T06:00:00Z",
    updatedAt: "2026-10-08T06:00:00Z",
  },
  {
    id: "TASK-107",
    title: "Team Standup & Sync",
    description: "Status report on sprint blockers and distributed message broker reliability.",
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "medium",
    status: "completed",
    dueDate: "2026-10-08",
    dueTime: "09:00",
    durationMinutes: 30,
    tags: ["meeting", "sync"],
    createdAt: "2026-10-08T08:00:00Z",
    updatedAt: "2026-10-08T09:30:00Z",
  },
  {
    id: "TASK-108",
    title: "API Testing & Load Profiling",
    description: "Stress test endpoint /v2/telemetry with 5,000 rps via k6 and measure p99 latency.",
    projectId: "proj-2",
    projectName: "FluentX",
    priority: "high",
    status: "completed",
    dueDate: "2026-10-08",
    dueTime: "14:00",
    durationMinutes: 90,
    tags: ["testing", "k6", "latency"],
    createdAt: "2026-10-08T10:00:00Z",
    updatedAt: "2026-10-08T15:30:00Z",
  },
  {
    id: "TASK-109",
    title: "Review deployment configuration",
    description: "Double check Docker compose overlay and Kubernetes ingress secrets.",
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "urgent",
    status: "pending",
    dueDate: "2026-10-06",
    dueTime: "12:00",
    durationMinutes: 45,
    tags: ["devops", "k8s", "infra"],
    createdAt: "2026-10-05T09:00:00Z",
    updatedAt: "2026-10-06T12:00:00Z",
  },
];

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: "EV-01",
    title: "TEAM STANDUP",
    startTime: "09:00",
    endTime: "09:30",
    date: "2026-10-08",
    status: "completed",
    projectName: "SynaptiQ",
    description: "Sprint alignment and blocker triage",
  },
  {
    id: "EV-02",
    title: "SYNAPTIQ BACKEND SYNC",
    startTime: "10:30",
    endTime: "11:45",
    date: "2026-10-08",
    status: "completed",
    projectName: "SynaptiQ",
    description: "Architecture breakdown with frontend leads",
  },
  {
    id: "EV-03",
    title: "API TESTING & PROFILING",
    startTime: "14:00",
    endTime: "15:30",
    date: "2026-10-08",
    status: "completed",
    projectName: "FluentX",
    description: "Locust & k6 test analysis",
  },
  {
    id: "EV-04",
    title: "WORKOUT SESSION",
    startTime: "18:30",
    endTime: "19:30",
    date: "2026-10-08",
    status: "current",
    projectName: "Personal",
    description: "Strength & conditioning circuit",
  },
  {
    id: "EV-05",
    title: "FASTAPI ARCHITECTURE DEEP DIVE",
    startTime: "21:00",
    endTime: "22:15",
    date: "2026-10-08",
    status: "upcoming",
    projectName: "Learning",
    description: "Chapter 4: Async generators and lifespan contexts",
  },
];

export const INITIAL_DUTIES: Duty[] = [
  {
    id: "DUTY-01",
    title: "Review team progress",
    frequency: "weekly",
    recurrenceText: "Every Friday",
    nextOccurrence: "Oct 09, 2026",
    lastCompleted: "Oct 02, 2026",
    completionStreak: 6,
    history: [
      { date: "Oct 02", completed: true },
      { date: "Sep 25", completed: true },
      { date: "Sep 18", completed: true },
      { date: "Sep 11", completed: true },
    ],
    projectId: "proj-1",
  },
  {
    id: "DUTY-02",
    title: "Plan next week",
    frequency: "weekly",
    recurrenceText: "Every Sunday",
    nextOccurrence: "Oct 11, 2026",
    lastCompleted: "Oct 04, 2026",
    completionStreak: 12,
    history: [
      { date: "Oct 04", completed: true },
      { date: "Sep 27", completed: true },
      { date: "Sep 20", completed: true },
    ],
  },
  {
    id: "DUTY-03",
    title: "Update project documentation",
    frequency: "weekly",
    recurrenceText: "Every Monday",
    nextOccurrence: "Oct 12, 2026",
    lastCompleted: "Oct 05, 2026",
    completionStreak: 4,
    history: [
      { date: "Oct 05", completed: true },
      { date: "Sep 28", completed: true },
      { date: "Sep 21", completed: false },
    ],
    projectId: "proj-2",
  },
  {
    id: "DUTY-04",
    title: "Review pending tasks & triage inbox",
    frequency: "daily",
    recurrenceText: "Every Evening",
    nextOccurrence: "Today at 22:30",
    lastCompleted: "Oct 07, 2026",
    completionStreak: 18,
    history: [
      { date: "Oct 07", completed: true },
      { date: "Oct 06", completed: true },
      { date: "Oct 05", completed: true },
    ],
  },
];

// Target timestamp calculations relative to Oct 08, 2026
const NOW_MS = 1791462000000; // Oct 08, 2026 approx

export const INITIAL_DEADLINES: Deadline[] = [
  {
    id: "DL-01",
    title: "OAuth redirect patch release",
    dueDate: "2026-10-07T18:00:00Z",
    targetTimestamp: NOW_MS - 86400000,
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "urgent",
    isOverdue: true,
    category: "OVERDUE",
  },
  {
    id: "DL-02",
    title: "SynaptiQ Backend Beta Deployment",
    dueDate: "2026-10-08T23:59:00Z",
    targetTimestamp: NOW_MS + 21600000, // ~6 hours
    projectId: "proj-1",
    projectName: "SynaptiQ",
    priority: "urgent",
    isOverdue: false,
    category: "TODAY",
  },
  {
    id: "DL-03",
    title: "FluentX Telemetry Service Validation",
    dueDate: "2026-10-11T12:00:00Z",
    targetTimestamp: NOW_MS + 225120000, // ~2.6 days
    projectId: "proj-2",
    projectName: "FluentX",
    priority: "high",
    isOverdue: false,
    category: "THIS WEEK",
  },
  {
    id: "DL-04",
    title: "FastAPI Concurrency Exam & Benchmark",
    dueDate: "2026-10-18T18:00:00Z",
    targetTimestamp: NOW_MS + 864000000, // ~10 days
    projectId: "proj-4",
    projectName: "Learning",
    priority: "medium",
    isOverdue: false,
    category: "UPCOMING",
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: "GOAL-01",
    title: "Backend Engineering",
    description: "Master high-throughput distributed systems, event-driven pipelines, and async FastAPI services.",
    progress: 72,
    targetDate: "Nov 30, 2026",
    category: "engineering",
    milestones: [
      { id: "m1", title: "Redis connection pool rate-limiting", completed: true },
      { id: "m2", title: "Sub-20ms p99 endpoint latency", completed: true },
      { id: "m3", title: "Distributed tracing with OpenTelemetry", completed: false },
      { id: "m4", title: "Chaos test fault-tolerance verification", completed: false },
    ],
  },
  {
    id: "GOAL-02",
    title: "Personal Fitness",
    description: "Achieve functional conditioning, mobility benchmarks, and consistent daily recovery discipline.",
    progress: 54,
    targetDate: "Dec 31, 2026",
    category: "fitness",
    milestones: [
      { id: "m5", title: "50 consecutive pushups with strict tempo", completed: true },
      { id: "m6", title: "5k continuous run under 22 minutes", completed: true },
      { id: "m7", title: "Maintain 85+ sleep readiness for 30 consecutive days", completed: false },
    ],
  },
  {
    id: "GOAL-03",
    title: "Learning & Systems Research",
    description: "Deep research into LLM agentic tool calling architectures and memory virtualization.",
    progress: 63,
    targetDate: "Dec 15, 2026",
    category: "learning",
    milestones: [
      { id: "m8", title: "Read 12 core papers on agentic reasoning", completed: true },
      { id: "m9", title: "Implement toy agent runtime with persistent memory", completed: true },
      { id: "m10", title: "Publish open source benchmark on memory overhead", completed: false },
    ],
  },
  {
    id: "GOAL-04",
    title: "Production Projects Delivery",
    description: "Launch SynaptiQ and FluentX core modules with 99.9% uptime SLA.",
    progress: 80,
    targetDate: "Oct 31, 2026",
    category: "career",
    milestones: [
      { id: "m11", title: "SynaptiQ alpha testing signoff", completed: true },
      { id: "m12", title: "FluentX streaming telemetry POC", completed: true },
      { id: "m13", title: "Public beta rollout", completed: false },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Reminder",
    message: "SYNAPTIQ BACKEND starts in 15 minutes.",
    timestamp: "10 min ago",
    type: "reminder",
    category: "REMINDERS",
    read: false,
  },
  {
    id: "notif-2",
    title: "Deadline",
    message: "API testing is due today.",
    timestamp: "2 hours ago",
    type: "deadline",
    category: "DEADLINES",
    read: false,
  },
  {
    id: "notif-3",
    title: "System",
    message: "Local node state synced with distributed cache.",
    timestamp: "4 hours ago",
    type: "system",
    category: "SYSTEM",
    read: true,
  },
  {
    id: "notif-4",
    title: "Overdue Alert",
    message: "Fix OAuth redirect was due yesterday at 18:00.",
    timestamp: "1 day ago",
    type: "deadline",
    category: "DEADLINES",
    read: true,
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    timestamp: "18:42",
    date: "2026-10-08",
    action: "Completed",
    targetTitle: "API testing & load profiling",
    targetType: "task",
    details: "All 5k rps k6 runs succeeded with 0 errors",
  },
  {
    id: "act-2",
    timestamp: "17:15",
    date: "2026-10-08",
    action: "Started",
    targetTitle: "SynaptiQ backend implementation",
    targetType: "task",
    details: "Started token bucket rate limiter module",
  },
  {
    id: "act-3",
    timestamp: "15:03",
    date: "2026-10-08",
    action: "Rescheduled",
    targetTitle: "Workout session",
    targetType: "event",
    details: "Moved to 18:30 to accommodate API profiling",
  },
  {
    id: "act-4",
    timestamp: "11:20",
    date: "2026-10-08",
    action: "Completed",
    targetTitle: "Team Standup & Sync",
    targetType: "task",
    details: "Blockers cleared for authentication sprint",
  },
  {
    id: "act-5",
    timestamp: "09:05",
    date: "2026-10-08",
    action: "Created",
    targetTitle: "Review backend API",
    targetType: "task",
    details: "Priority set to High",
  },
];

export const INITIAL_DAILY_REVIEW: DailyReview = {
  date: "2026-10-08",
  completedTasks: 7,
  incompleteTasks: 2,
  postponedTasks: 1,
  overdueTasks: 1,
  wentWellNotes: "Completed high-priority API load profiling with zero dropped requests. Rate limiting architectural spike finished cleanly.",
  remainsNotes: "OAuth redirect bug needs final state parameter verification before deployment merge.",
  tomorrowNotes: "Deploy SynaptiQ v0.9-beta to staging and lead architecture walkthrough.",
};

export const INITIAL_WEEKLY_REVIEW: WeeklyReview = {
  weekRange: "Oct 05 — Oct 11, 2026",
  tasksCompleted: 28,
  tasksPostponed: 4,
  deadlinesMet: 5,
  overdueTasks: 1,
  mostActiveProjects: [
    { name: "SynaptiQ", taskCount: 16 },
    { name: "FluentX", taskCount: 8 },
    { name: "Personal", taskCount: 4 },
  ],
  goalsProgress: [
    { title: "Backend Engineering", progress: 72 },
    { title: "Personal Fitness", progress: 54 },
    { title: "Learning & Systems Research", progress: 63 },
  ],
  upcomingCommitments: [
    "Friday 17:00: Team weekly progress review",
    "Sunday 19:00: Next week sprint planning",
    "Monday 10:00: Telemetry beta release demo",
  ],
};
